services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus.yml
  
  app:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
    ports:
      - "8090:8090"
    depends_on:
      - prometheus
    networks:
      - url-shortener-shared-network

networks:
  url-shortener-shared-network:
    external: true
  